version: "2"
services:
  anagram-search:
    image: anagram-search:local
    container_name: anagram-search
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always