# Group Anagrams

## Anagrams [/anagrams/:word.json{?limit}]

Provides a resource for searching and filtering anagrams of a given word.
Anagrams will only be returned if they are actual English words as defined by the corpus.

### List Anagrams [GET]

Returns all anagrams of a provided word, excluding the provided word itself.
If no limit is specified the maximium number of results will be 10,000.

+ Parameters

    + limit: `1` (number, optional) - number of results to return.

+ Request
    + Headers

            Host:localhost:3000
            Accept:*/*

    + Body


+ Response 200
    + Headers

            Content-Type:application/json; charset=utf-8
            Content-Length:28

    + Body

            {"anagrams":["dear","dare"]}
