# Group Anagrams

Returns anagrams of a provided word.
Anagrams will only be returned if they are actual English words as defined by the corpus.

# GET /anagrams/read.json
+ Request
    + Headers

            Host:localhost:3000
            User-Agent:curl/7.54.0
            Accept:*/*

    + Body


+ Response 200
    + Headers

            X-Powered-By:Express
            Content-Type:application/json; charset=utf-8
            Content-Length:28
            ETag:W/"1c-s+6jar/Rgp2b/TCReYLBwy9TNL8"
            Date:Fri, 07 Sep 2018 00:35:50 GMT
            Connection:keep-alive

    + Body

            {"anagrams":["dear","dare"]}





# GET /anagrams/read.json?limit=1
+ Request
    + Headers

            Host:localhost:3000
            User-Agent:curl/7.54.0
            Accept:*/*

    + Body



+ Response 200
    + Headers

            X-Powered-By:Express
            Content-Type:application/json; charset=utf-8
            Content-Length:21
            ETag:W/"15-7e0pJzVQS/kwfhNgoE7lkUIhD4M"
            Date:Fri, 07 Sep 2018 00:37:07 GMT
            Connection:keep-alive

    + Body

            {"anagrams":["dear"]}