FORMAT: A1

# Anagram-Search

An API that allows fast searches for Anagrams.
Anagrams are checked against a corpus to ensure only Enlish language words are returned.

(What's an anagram? See: https://en.wikipedia.org/wiki/Anagram)

<!-- include(anagrams.apib) -->
<!-- include(words.apib) -->