# Group Seed

Provides a resource for re-seeding the database in the event it has been dropped.

## Seed [/seed]

### Seed the database from the dictionary file [POST]
+ Request
    + Headers

            Host:localhost:3000
            Accept:*/*
            Content-Type:application/json
            Content-Length:0

    + Body

            {}


+ Response 200
    + Headers

            Content-Type:application/json; charset=utf-8

    + Body

            "import succeeded"