# Group Words

Provides a resource for creating  sets of words and deleting words from the corpus.

## Words [/words]

### Create Set of Words [POST]
+ Request
    + Headers

            Host:localhost:3000
            Accept:*/*
            Content-Type:application/json

    + Body

            { "words": ["read", "dear", "dare"] }

+ Response 201
    + Headers

            Content-Length:0

    + Body


### Drop entire Database [DELETE]

+ Request
    + Headers

            Host:localhost:3000
            Accept:*/*

    + Body

+ Response 204
    + Headers

            Connection:keep-alive

    + Body

## Words [/words/:word.json{?drop}]

### Remove words from set or drop a set [DELETE]

+ Parameters

    + drop: `all` - (string, optional) - if provided, will drop all words in the set by the :word key

+ Request
    + Headers

            Host:localhost:3000
            Accept:*/*
            Content-Type:application/json

    + Body


+ Response 204
    + Headers

            X-Powered-By:Express
            Connection:keep-alive

    + Body



